### ISSUE TITLE
Could not load type 'Microsoft.AspNet.Http.Features.FeatureCollectionExtensions'

### ISSUE THREAD

**Issue by dopare** [aspnet/StaticFiles#106]
Running on latest dnx-coreclr-win-x64-rc2-16357 build

```
info: Microsoft.AspNet.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.ico'. Physical path: '***'
fail: Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.TypeLoadException: Could not load type 'Microsoft.AspNet.Http.Features.FeatureCollectionExtensions' from assembly 'Microsoft.AspNet.Http.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
         at Microsoft.AspNet.StaticFiles.StaticFileContext.<SendAsync>d__44.MoveNext()
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
         at Microsoft.AspNet.StaticFiles.StaticFileContext.SendAsync()
         at Microsoft.AspNet.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__3.MoveNext()
```

I have attached StaticFiles package manually via global.json and it worked.

**Comment by davidfowl** [comment]
Sounds like you have a version mismatch. Can you make a project on github that shows the repro?

**Comment by dopare** [comment]
Pushed latest codebase to https://github.com/EpamArmenia/OfficeManager

**Comment by davidfowl** [comment]
That repository doesn't have a `nuget.config` so it's unlikely that it will even build for me.

**Comment by dopare** [comment]
@davidfowl sorry, updated the repo with `nuget.config`

**Comment by dopare** [comment]
Adding `<clear/>` in `nuget.config` resolved the issue.
@davidfowl thanks for help
