### ISSUE TITLE
Error:  Unable to resolve service for type 'System.Text.Encodings.Web.HtmlEncoder'

### ISSUE THREAD

**Issue by NotMyself** [aspnet/StaticFiles#131]
## Steps to reproduce
`git clone https://github.com/NotMyself/RC2Error`
`cd RC2Error` & `dotnet restore`
`dotnet run`

## Expected  behavior
Project should compile and run allowing me to browse the wwwroot directory

## Actual behavior
Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'System.Text.Encodings.Web.HtmlEncoder' while attempting to activate 'Microsoft.AspNetCore.StaticFiles.DirectoryBrowserMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at UIMvc.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

**Windows via PowerShell**
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14342
 OS Platform: Windows
 RID:         win10-x64

![selfie-0](http://i.imgur.com/eKvZ23D.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by pakrym** [comment]
Add`AddDirectoryBrowser` call to `ConfigureServices`.

```
public class Startup
{
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDirectoryBrowser();
        }

        ...
}
```

**Comment by NotMyself** [comment]
That was it. Thanks.
