### ISSUE TITLE
Handle and log OperationCanceledExceptions thrown due to client disconnects

### ISSUE THREAD

**Issue by halter73** [aspnet/StaticFiles#150]
_From @anpete on April 14, 2016 5:32_

Not sure if this is expected, so filing just in case. While investigating our internal MusicStore stress scenario I'm seeing an OperationCanceledException raised occasionally when the number of clients > ~50.

Stack:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
warn: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      The response has already started, the error handler will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKR44KL0RBVP": An unhandled exception was thrown by the application.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

_Copied from original issue: aspnet/KestrelHttpServer#748_

**Comment by halter73** [comment]
_From @Eilon on April 14, 2016 7:21_

This magic number 50 sounds suspiciously like https://github.com/aspnet/Coherence-Signed/issues/268, not that I have any idea whether it's related at all.

**Comment by halter73** [comment]
_From @mikeharder on April 19, 2016 18:50_

@anpete: A few questions:
* Are you using HTTP or HTTPS?
* Can you share steps to reproduce this?
* How often does it repro?
* Does this server exception have any impact on the client?  Does the client get a 500 response when this happens?

**Comment by halter73** [comment]
_From @anpete on April 19, 2016 20:5_

@mikeharder Looks like this is no longer repro'ing - after https://github.com/aspnet/MusicStore/commit/fb4fadb0b10301b09326b8a9f78b6f1893210cb3

Let me know if you still want to investigate.

**Comment by halter73** [comment]
_From @mikeharder on April 20, 2016 17:59_

It's by design that this exception is raised if a client disconnects before reading a full response, which is likely what was happening before your changes.

**Comment by halter73** [comment]
_From @gdoron on August 14, 2016 10:17_

@mikeharder  @Eilon 
If it is caused by client disconnection, the level shouldn't be error.
It pollutes our log with stuff that aren't really errors and no actions need to be taken.

Am I right?

**Comment by halter73** [comment]
_From @mikeharder on August 15, 2016 18:8_

@halter73, @cesarbs: What log level is used for client disconnects?  I think they should be `Information` or lower.

**Comment by halter73** [comment]
_From @benaadams on August 15, 2016 19:19_

Change the exception type? (e.g. OperationCanceledException->HttpDisconnectException) so it can be distinguished from an OperationCanceledException arising in user code?

**Comment by halter73** [comment]
_From @Tratcher on August 15, 2016 20:25_

No, you don't want to mess up the Stream/Task exception contract.

**Comment by halter73** [comment]
_From @benaadams on August 15, 2016 20:27_

Could still catch a derived exception with `catch (OperationCanceledException ex)` just allows for differentiation?

**Comment by halter73** [comment]
Agreed. I think StaticFiles should `catch (OperationCanceledException ex)` and check `HttpContext.RequestAborted.IsCancellationRequested`. If the `RequestAborted` token is canceled, log something about a client disconnect at an information or lower log level. Otherwise, rethrow.

**Comment by halter73** [comment]
_From @Tratcher on August 15, 2016 22:52_

We'd have to write that kind of code into every middleware and framework. That's a very expensive solution to an otherwise minor problem.

**Comment by halter73** [comment]
@Tratcher Only middleware that writes responses while passing in the RequestAborted token to WriteAsync/SendFile needs to change. What other than StaticFiles actually does that? I'm guessing there's not too many other examples. I've seen several complaints for StaticFiles throwing an uncaught `OperationCanceledException`, but never for anything else.

It's really not necessary to pass in the RequestAborted token when writing small or cached responses since the following written bytes will be quickly thrown away.

**Comment by halter73** [comment]
_From @muratg on August 17, 2016 22:6_

I asked @halter73 to file a bug on StaticFiles to continue the discussion there. We can reach the decision there later.

**Comment by Tratcher** [comment]
@halter73 what happened to all the comments?

**Comment by halter73** [comment]
They're in the old issue. Would you prefer I close this and reopen with comments?

**Comment by Tratcher** [comment]
Or re-word this one to explain the proposal

**Comment by halter73** [comment]
Ideally the client disconnect log message would have a LogLevel lower than error, since the main motivation for this issue is to clean up logs. I would go with LogLevel.Information, since that is how Kestrel logs most connection errors. It might also be helpful to indicate what file was being served.

**Comment by gdoron** [comment]
I personally think it should be debug.
There is no information an application owner should care about except from debugging nor there's an action he should or even can do.
It's completely out of scope of applications.
(Unlike timing for example)

**Comment by Tratcher** [comment]
The other thing to sort out here is OperationCancelledException vs TaskCanceledException. Kestrel uses the former and WebListener the later.

**Comment by halter73** [comment]
@Tratcher Did you mean that Kestrel uses the latter `TaskCanceledException`? I don't think Kestrel uses `OperationCanceledException` anywhere.

**Comment by Tratcher** [comment]
The OperationCanceledException may be coming directly from StreamCopyOperation

**Comment by Tratcher** [comment]
TaskCanceledException derives from OperationCanceledException, so anything that deals with OCE will also handle TCE

**Comment by halter73** [comment]
Sure, but anything that Kestrel throws directly will be the derived type.

**Comment by gdoron** [comment]
If I understood the code correctly, you ended up making the log debug as I suggested, right?

**Comment by Tratcher** [comment]
Yes https://github.com/aspnet/StaticFiles/commit/bbf1478821c11ecdcad776dad085d6ee09d8f8ee#diff-991aec26255237cd6dbfa787d0995a2aR85
