### ISSUE TITLE
StaticFileContext.SendAsync doesn't catch TaskCanceledException.

### ISSUE THREAD

**Issue by SergeySomkov** [aspnet/StaticFiles#222]
After client aborts http request, StreamCopyOperation.CopyToAsync throws TaskCanceledException.
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendAsync>d__46.MoveNext()
```
The exception is not handled inside StaticFileContext.SendAsync. It is handled by Kestrel and it logs the following event:
- Connection id "{ConnectionId}": An unhandled exception was thrown by the application.
- LogLevel: Error
- Category: Microsoft.AspNetCore.Server.Kestrel
- EventId: 13

I'm wondering how is it even possible since StaticFileContext.SendAsync contains the following code:
```
try
{
  using (var readStream = _fileInfo.CreateReadStream())
  {
    // Larger StreamCopyBufferSize is required because in case of FileStream readStream isn't going to be buffering
    await StreamCopyOperation.CopyToAsync(readStream, _response.Body, _length, StreamCopyBufferSize, _context.RequestAborted);
  }
}
catch (OperationCanceledException ex)
{
  _logger.LogWriteCancelled(ex);
  // Don't throw this exception, it's most likely caused by the client disconnecting.
  // However, if it was cancelled for any other reason we need to prevent empty responses.
  _context.Abort();
}
```

**Comment by SergeySomkov** [comment]
class TaskCanceledException : OperationCanceledException
Sorry...

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2439
